version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 880651758906.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t dock-image .
      - docker tag dock-image 880651758906.dkr.ecr.us-east-1.amazonaws.com/docker-repo
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 880651758906.dkr.ecr.us-east-1.amazonaws.com/docker-repo
      - printf '[{"name":"cont1","imageUri":"%s"}]' 880651758906.dkr.ecr.us-east-1.amazonaws.com/docker-repo:latest > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
